package com.zakiy.platform.ui.school

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import com.zakiy.platform.R
import com.zakiy.platform.network.NetworkModule
import com.zakiy.platform.network.dto.BulkAddRequest
import com.zakiy.platform.network.dto.SchoolClass
import com.zakiy.platform.network.dto.SchoolStudent
import com.zakiy.platform.ui.components.CredentialBox
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SchoolStudentsScreen(onBack: () -> Unit) {
    var students by remember { mutableStateOf<List<SchoolStudent>>(emptyList()) }
    var classes by remember { mutableStateOf<List<SchoolClass>>(emptyList()) }
    var selectedClassId by remember { mutableStateOf<String?>(null) }
    var bulkNames by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<List<Pair<String, String>>>(emptyList()) }
    var classMenuExpanded by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()

    suspend fun load() {
        students = runCatching { NetworkModule.backendApi.schoolStudents().students }.getOrDefault(emptyList())
        classes = runCatching { NetworkModule.backendApi.schoolClasses().classes }.getOrDefault(emptyList())
        if (selectedClassId == null) selectedClassId = classes.firstOrNull()?.id
    }
    LaunchedEffect(Unit) { load() }
    val className = { id: String? -> classes.firstOrNull { it.id == id }?.name ?: "—" }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.tab_students)) },
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.Filled.ArrowBack, contentDescription = null) } },
            )
        },
    ) { padding ->
        Column(modifier = Modifier.fillMaxSize().padding(padding).padding(16.dp)) {
            Row {
                Text(stringResource(R.string.tab_classes) + ": " + className(selectedClassId), modifier = Modifier.weight(1f))
                androidx.compose.material3.TextButton(onClick = { classMenuExpanded = true }) { Text("▾") }
                DropdownMenu(expanded = classMenuExpanded, onDismissRequest = { classMenuExpanded = false }) {
                    classes.forEach { c ->
                        DropdownMenuItem(text = { Text(c.name) }, onClick = { selectedClassId = c.id; classMenuExpanded = false })
                    }
                }
            }
            OutlinedTextField(
                value = bulkNames,
                onValueChange = { bulkNames = it },
                label = { Text(stringResource(R.string.tab_bulk_students)) },
                minLines = 3,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(modifier = Modifier.size(8.dp))
            OutlinedButton(
                onClick = {
                    val classId = selectedClassId ?: return@OutlinedButton
                    val names = bulkNames.lines().map { it.trim() }.filter { it.isNotEmpty() }
                    if (names.isEmpty()) return@OutlinedButton
                    scope.launch {
                        val result = runCatching {
                            NetworkModule.backendApi.schoolBulkAddStudents(BulkAddRequest(classId, names))
                        }.getOrNull()
                        if (result != null) {
                            generated = result.students.map { it.username to it.password }
                            bulkNames = ""
                            load()
                        }
                    }
                },
                modifier = Modifier.fillMaxWidth(),
            ) { Text(stringResource(R.string.tab_bulk_students)) }

            LazyColumn(modifier = Modifier.weight(1f)) {
                items(generated) { (username, password) -> CredentialBox("✅", username, password) }
                items(students, key = { it.userId }) { student ->
                    Card(modifier = Modifier.fillMaxWidth().padding(vertical = 6.dp)) {
                        Column(modifier = Modifier.padding(14.dp)) {
                            Text(student.fullName ?: student.username, style = MaterialTheme.typography.titleMedium)
                            Text(student.username, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            Text(className(student.classId), style = MaterialTheme.typography.bodyMedium)
                            Row {
                                OutlinedButton(onClick = {
                                    scope.launch {
                                        val reset = runCatching { NetworkModule.backendApi.schoolResetAccountPassword(student.userId) }.getOrNull()
                                        if (reset != null) generated = listOf(reset.identifier to reset.password) + generated
                                    }
                                }) { Text(stringResource(R.string.btn_reset_password)) }
                                Spacer(modifier = Modifier.size(6.dp))
                                OutlinedButton(onClick = {
                                    scope.launch {
                                        runCatching { NetworkModule.backendApi.schoolDeleteAccount(student.userId) }
                                        load()
                                    }
                                }) { Text(stringResource(R.string.delete)) }
                            }
                        }
                    }
                }
            }
        }
    }
}
